services:
  postgres:
    image: postgres:16
    container_name: cloud_drive_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_drive
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
